cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
Adding new merge properties to components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/2)
=> Merge properties

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/3)
=> Updated component version numbers.

cpp/OcvPersonDetection/CMakeLists.txt, cpp/OcvPersonDetection/PersonDetection.cpp, cpp/OcvPersonDetection/tracking/dataReader.cpp, cpp/motion/MogMotionDetection/CMakeLists.txt, cpp/motion/MogMotionDetection/MotionDetection_MOG2.cpp, cpp/motion/MogMotionDetection/MotionDetection_MOG2.h, cpp/motion/MogMotionDetection/sample_mog_motion_detector.cpp, cpp/motion/STRUCK/CMakeLists.txt, cpp/motion/STRUCK/vot.hpp, cpp/motion/SubsenseMotionDetection/CMakeLists.txt, cpp/motion/SubsenseMotionDetection/MotionDetection_Subsense.cpp, cpp/motion/SubsenseMotionDetection/MotionDetection_Subsense.h, cpp/motion/SubsenseMotionDetection/SubSense/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/5)
=> Updated for OpenCV 3.2.

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/8)
=> Add supportsBatchProcessing to descriptors.

cpp/OcvPersonDetection/PersonDetection.cpp, cpp/OcvPersonDetection/PersonDetection.h, cpp/OcvPersonDetection/plugin-files/config/mpfOcvPersonDetection.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/11)
=> Make OcvPerson component use auto frame skip

cpp/motion/MogMotionDetection/sample_mog_motion_detector.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/13)
=> Updated sample_mog_motion_detector.

cpp/motion/MogMotionDetection/MotionDetection_MOG2.cpp, cpp/motion/MogMotionDetection/MotionDetection_MOG2.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/12)
=> Make MoG use frame skipper

cpp/motion/SubsenseMotionDetection/MotionDetection_Subsense.cpp, cpp/motion/SubsenseMotionDetection/MotionDetection_Subsense.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/14)
=> Make SubSense use frame skipper

cpp/motion/MogMotionDetection/sample_mog_motion_detector.cpp, cpp/motion/SubsenseMotionDetection/sample_subsense_motion_detector.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/15)
=> Updated MOG and SuBSENSE sample binaries.

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/18)
=> Update readme develop

cpp/OcvPersonDetection/CMakeLists.txt, cpp/motion/MogMotionDetection/CMakeLists.txt, cpp/motion/STRUCK/CMakeLists.txt, cpp/motion/SubsenseMotionDetection/CMakeLists.txt, cpp/motion/SubsenseMotionDetection/SubSense/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/19)
=> Updated for OpenCV 3.3.

cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/20)
=> Enable feed forward in Mog and Subsense.

cpp/OcvPersonDetection/PersonDetection.cpp, cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/OcvPersonDetection/tracking/detector.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/21)
=> Enable feed forward for OcvPerson

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/23)
=> Enable USE_KEY_FRAMES.

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/22)
=> updated version numbers in descriptor files, issue #264

cpp/OcvPersonDetection/PersonDetection.cpp, cpp/motion/MogMotionDetection/MotionDetection_MOG2.cpp, cpp/motion/SubsenseMotionDetection/MotionDetection_Subsense.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/29)
=> Corrected log statement when tracks are found.

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/31)
=> Updated descriptor file to remove launchArgs.

cpp/OcvPersonDetection/CMakeLists.txt, cpp/motion/MogMotionDetection/CMakeLists.txt, cpp/motion/SubsenseMotionDetection/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/32)
=> Update CMakeLists to use new signature for configure_mpf_component.

cpp/motion/CMakeLists.txt, cpp/motion/SubsenseMotionDetection/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/35)
=> Fixed issue where subsense could not be built by itself.

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/38)
=> Updated version numbers to 2.0.0.

README.md, cpp/OcvPersonDetection/LICENSE, cpp/motion/LICENSE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/40)
=> Added Python SDK to README.

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/41)
=> Add FRAME_RATE_CAP to descriptors

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/42)
=> Updated version to 2.1.0.

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/45)
=> Updated version to 3.0.0.

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/46)
=> Track merging is now only applied to videos.

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/49)
=> Update version to 4.1.0.

cpp/motion/SubsenseMotionDetection/MotionDetection_Subsense.cpp, cpp/motion/SubsenseMotionDetection/StreamingMotionDetection_Subsense.cpp, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/sample_subsense_motion_detector.cpp, cpp/motion/SubsenseMotionDetection/test/test_subsense_motion_detection.cpp, cpp/motion/Utils/MotionDetectionUtils.cpp, cpp/motion/Utils/MotionDetectionUtils.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/57)
=> Hotfix merge master/subsense confidence

cpp/OcvPersonDetection/.dockerignore, cpp/OcvPersonDetection/Dockerfile, cpp/motion/.dockerignore, cpp/motion/MogMotionDetection/Dockerfile, cpp/motion/SubsenseMotionDetection/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/55)
=> Changes for improved docker build2

cpp/motion/SubsenseMotionDetection/MotionDetection_Subsense.cpp, cpp/motion/SubsenseMotionDetection/StreamingMotionDetection_Subsense.cpp, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/sample_subsense_motion_detector.cpp, cpp/motion/SubsenseMotionDetection/test/test_subsense_motion_detection.cpp, cpp/motion/Utils/MotionDetectionUtils.cpp, cpp/motion/Utils/MotionDetectionUtils.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/58)
=> Hotfix merge develop/subsense confidence

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/65)
=> Update versions to 5.1.

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/66)
=> Update versions to 5.1. (#65)

cpp/OcvPersonDetection/CMakeLists.txt, cpp/OcvPersonDetection/PersonDetection.cpp, cpp/OcvPersonDetection/tracking/appTemplate.cpp, cpp/OcvPersonDetection/tracking/multiTrackAssociation.cpp, cpp/OcvPersonDetection/tracking/tracker.cpp, cpp/OcvPersonDetection/tracking/tracker.h, cpp/OcvPersonDetection/tracking/util.h, cpp/motion/MogMotionDetection/CMakeLists.txt, cpp/motion/MogMotionDetection/MotionDetection_MOG2.cpp, cpp/motion/STRUCK/CMakeLists.txt, cpp/motion/STRUCK/GraphUtils/GraphUtils.cpp, cpp/motion/STRUCK/GraphUtils/GraphUtils.h, cpp/motion/STRUCK/ImageRep.cpp, cpp/motion/STRUCK/LaRank.cpp, cpp/motion/STRUCK/LaRank.h, cpp/motion/SubsenseMotionDetection/CMakeLists.txt, cpp/motion/SubsenseMotionDetection/MotionDetection_Subsense.cpp, cpp/motion/SubsenseMotionDetection/SubSense/CMakeLists.txt, cpp/motion/SubsenseMotionDetection/SubSense/bgfg_segm.cpp, cpp/motion/Utils/MotionDetectionUtils.cpp
Associated PRs:
- https://github.com/openmpf/openmpf/pull/1136
- https://github.com/openmpf/openmpf-docker/pull/108
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/89
- https://github.com/openmpf/openmpf-python-component-sdk/pull/37
- https://github.com/openmpf/openmpf-components/pull/174
- https://github.com/openmpf/openmpf-contrib-components/pull/63
Issues:
- https://github.com/openmpf/openmpf/issues/1101
- https://github.com/openmpf/openmpf/issues/1073
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/63)
=> OpenCV4 upgrade with CUDA

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/67)
=> Update versions to 6.0.

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/70)
=> Update versions to 6.1.

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
**Issues:**
- https://github.com/openmpf/openmpf/issues/1322
- https://github.com/openmpf/openmpf/pull/1321
- https://github.com/openmpf/openmpf-components/pull/253
- https://github.com/openmpf/openmpf-contrib-components/pull/72
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/106
- https://github.com/openmpf/openmpf-python-component-sdk/pull/49
- https://github.com/openmpf/openmpf-java-component-sdk/pull/53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/72)
=> Update versions to 6.2.

README.md
**Issues:**
- https://github.com/openmpf/openmpf/issues/1351
- https://github.com/openmpf/openmpf.github.io/pull/130
- https://github.com/openmpf/openmpf-components/pull/259
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/73)
=> Clarify the difference between Docker and non-Docker behaviors.

cpp/OcvPersonDetection/plugin-files/descriptor/descriptor.json, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
**Issues:**
- https://github.com/openmpf/openmpf/issues/1401
- https://github.com/openmpf/openmpf/pull/1400
- https://github.com/openmpf/openmpf-components/pull/279
- https://github.com/openmpf/openmpf-contrib-components/pull/75
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/107
- https://github.com/openmpf/openmpf-python-component-sdk/pull/56
- https://github.com/openmpf/openmpf-java-component-sdk/pull/54
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/75)
=> Update versions to 6.3.

cpp/motion/MogMotionDetection/CMakeLists.txt, cpp/motion/STRUCK/CMakeLists.txt, cpp/motion/STRUCK/Tracker.cpp, cpp/motion/STRUCK/struck.cpp, cpp/motion/SubsenseMotionDetection/CMakeLists.txt, cpp/motion/SubsenseMotionDetection/SubSense/CMakeLists.txt
**Issues:**
- https://github.com/openmpf/openmpf/issues/1519
- https://github.com/openmpf/openmpf/pull/1518
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/112
- https://github.com/openmpf/openmpf-docker/pull/165
- https://github.com/openmpf/openmpf-components/pull/293
- https://github.com/openmpf/openmpf-contrib-components/pull/78
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/78)
=> Hotfix/ocv 4.5.5

cpp/motion/MogMotionDetection/CMakeLists.txt, cpp/motion/STRUCK/CMakeLists.txt, cpp/motion/STRUCK/Tracker.cpp, cpp/motion/STRUCK/struck.cpp, cpp/motion/SubsenseMotionDetection/CMakeLists.txt, cpp/motion/SubsenseMotionDetection/SubSense/CMakeLists.txt
Merges: https://github.com/openmpf/openmpf-contrib-components/pull/78
**Issues:**
- https://github.com/openmpf/openmpf/issues/1519
- https://github.com/openmpf/openmpf/pull/1523
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/113
- https://github.com/openmpf/openmpf-docker/pull/166
- https://github.com/openmpf/openmpf-components/pull/294
- https://github.com/openmpf/openmpf-contrib-components/pull/79
- https://github.com/openmpf/openmpf.github.io/pull/150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/79)
=> Hf merge/ocv 4.5.5

.gitignore, cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
**Issues:**
- https://github.com/openmpf/openmpf/issues/1552
- https://github.com/openmpf/openmpf/pull/1551
- https://github.com/openmpf/openmpf-components/pull/300
- https://github.com/openmpf/openmpf-contrib-components/pull/80
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/114
- https://github.com/openmpf/openmpf-java-component-sdk/pull/58
- https://github.com/openmpf/openmpf-python-component-sdk/pull/64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/80)
=> Update versions to 7.0.

NOTICE, cpp/CMakeLists.txt, cpp/ComponentSetup.cmake, cpp/motion/.dockerignore, cpp/motion/CMakeLists.txt, cpp/motion/MogMotionDetection/CMakeLists.txt, cpp/motion/MogMotionDetection/Dockerfile, cpp/motion/MogMotionDetection/MotionDetection_MOG2.cpp, cpp/motion/MogMotionDetection/MotionDetection_MOG2.h, cpp/motion/MogMotionDetection/sample_mog_motion_detector.cpp, cpp/motion/MogMotionDetection/test/CMakeLists.txt, cpp/motion/MogMotionDetection/test/test_mog_motion_detection.cpp, cpp/motion/NOTICE, cpp/motion/STRUCK/CMakeLists.txt, cpp/motion/STRUCK/struck.cpp, cpp/motion/STRUCK/struck.h, cpp/motion/SubsenseMotionDetection/CMakeLists.txt, cpp/motion/SubsenseMotionDetection/Dockerfile, cpp/motion/SubsenseMotionDetection/MotionDetection_Subsense.cpp, cpp/motion/SubsenseMotionDetection/MotionDetection_Subsense.h, cpp/motion/SubsenseMotionDetection/StreamingMotionDetection_Subsense.cpp, cpp/motion/SubsenseMotionDetection/StreamingMotionDetection_Subsense.h, cpp/motion/SubsenseMotionDetection/SubsenseUtils.cpp, cpp/motion/SubsenseMotionDetection/SubsenseUtils.h, cpp/motion/SubsenseMotionDetection/sample_subsense_motion_detector.cpp, cpp/motion/SubsenseMotionDetection/sample_subsense_streaming_motion_detector.cpp, cpp/motion/SubsenseMotionDetection/test/CMakeLists.txt, cpp/motion/SubsenseMotionDetection/test/test_subsense_motion_detection.cpp, cpp/motion/SubsenseMotionDetection/test/test_subsense_streaming_motion_detection.cpp
**Issues:**
- https://github.com/openmpf/openmpf/issues/1473
- https://github.com/openmpf/openmpf/pull/1555
- https://github.com/openmpf/openmpf-components/pull/302
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/115
- https://github.com/openmpf/openmpf-java-component-sdk/pull/59
- https://github.com/openmpf/openmpf-build-tools/pull/45
- https://github.com/openmpf/openmpf-contrib-components/pull/81
- https://github.com/openmpf/openmpf-docker/pull/171
- https://github.com/openmpf/openmpf-python-component-sdk/pull/65
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/81)
=> Update copyright to 2022.

cpp/motion/MogMotionDetection/MotionDetection_MOG2.cpp, cpp/motion/SubsenseMotionDetection/MotionDetection_Subsense.cpp, cpp/motion/SubsenseMotionDetection/StreamingMotionDetection_Subsense.cpp, cpp/motion/SubsenseMotionDetection/SubsenseUtils.cpp, cpp/motion/SubsenseMotionDetection/SubsenseUtils.h
**Issues:**
- https://github.com/openmpf/openmpf/issues/1569
- https://github.com/openmpf/openmpf/pull/1568
- https://github.com/openmpf/openmpf-components/pull/303
- https://github.com/openmpf/openmpf-contrib-components/pull/82
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/116
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/82)
=> Remove manually added job name from log messages.

cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
**Issues:**
- https://github.com/openmpf/openmpf/issues/1634
- https://github.com/openmpf/openmpf/pull/1633
- https://github.com/openmpf/openmpf-components/pull/314
- https://github.com/openmpf/openmpf-contrib-components/pull/85
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/118
- https://github.com/openmpf/openmpf-java-component-sdk/pull/60
- https://github.com/openmpf/openmpf-python-component-sdk/pull/70
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/85)
=> Update versions to 7.1.

cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
**Issues:**
- https://github.com/openmpf/openmpf/issues/1683
- https://github.com/openmpf/openmpf/pull/1682
- https://github.com/openmpf/openmpf-components/pull/330
- https://github.com/openmpf/openmpf-contrib-components/pull/87
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/120
- https://github.com/openmpf/openmpf-java-component-sdk/pull/62
- https://github.com/openmpf/openmpf-python-component-sdk/pull/75
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/87)
=> Update versions to 7.2.

cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
**Issues:**
- https://github.com/openmpf/openmpf/issues/1737
- https://github.com/openmpf/openmpf.github.io/pull/173
- https://github.com/openmpf/openmpf/pull/1738
- https://github.com/openmpf/openmpf-components/pull/345
- https://github.com/openmpf/openmpf-contrib-components/pull/89
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/122
- https://github.com/openmpf/openmpf-java-component-sdk/pull/64
- https://github.com/openmpf/openmpf-python-component-sdk/pull/76
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/89)
=> Update version numbers to 8.0.

cpp/motion/MogMotionDetection/CMakeLists.txt, cpp/motion/STRUCK/CMakeLists.txt, cpp/motion/SubsenseMotionDetection/CMakeLists.txt, cpp/motion/SubsenseMotionDetection/SubSense/CMakeLists.txt
**Issues:**
- https://github.com/openmpf/openmpf/issues/1785
- https://github.com/openmpf/openmpf/pull/1791
- https://github.com/openmpf/openmpf-docker/pull/211
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/123
- https://github.com/openmpf/openmpf-components/pull/362
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/90)
=> Update build to use OpenCV 4.9.0

cpp/motion/MogMotionDetection/plugin-files/descriptor/descriptor.json, cpp/motion/SubsenseMotionDetection/plugin-files/descriptor/descriptor.json
**Issues:**
- https://github.com/openmpf/openmpf/issues/1801
- https://github.com/openmpf/openmpf/pull/1802
- https://github.com/openmpf/openmpf-components/pull/367
- https://github.com/openmpf/openmpf-contrib-components/pull/91
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/125
- https://github.com/openmpf/openmpf-python-component-sdk/pull/79
- https://github.com/openmpf/openmpf-java-component-sdk/pull/65
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/91)
=> Update version numbers to 9.0.

NOTICE, cpp/CMakeLists.txt, cpp/ComponentSetup.cmake, cpp/motion/.dockerignore, cpp/motion/CMakeLists.txt, cpp/motion/MogMotionDetection/CMakeLists.txt, cpp/motion/MogMotionDetection/Dockerfile, cpp/motion/MogMotionDetection/MotionDetection_MOG2.cpp, cpp/motion/MogMotionDetection/MotionDetection_MOG2.h, cpp/motion/MogMotionDetection/sample_mog_motion_detector.cpp, cpp/motion/MogMotionDetection/test/CMakeLists.txt, cpp/motion/MogMotionDetection/test/test_mog_motion_detection.cpp, cpp/motion/NOTICE, cpp/motion/STRUCK/CMakeLists.txt, cpp/motion/STRUCK/struck.cpp, cpp/motion/STRUCK/struck.h, cpp/motion/SubsenseMotionDetection/CMakeLists.txt, cpp/motion/SubsenseMotionDetection/Dockerfile, cpp/motion/SubsenseMotionDetection/MotionDetection_Subsense.cpp, cpp/motion/SubsenseMotionDetection/MotionDetection_Subsense.h, cpp/motion/SubsenseMotionDetection/StreamingMotionDetection_Subsense.cpp, cpp/motion/SubsenseMotionDetection/StreamingMotionDetection_Subsense.h, cpp/motion/SubsenseMotionDetection/SubsenseUtils.cpp, cpp/motion/SubsenseMotionDetection/SubsenseUtils.h, cpp/motion/SubsenseMotionDetection/sample_subsense_motion_detector.cpp, cpp/motion/SubsenseMotionDetection/sample_subsense_streaming_motion_detector.cpp, cpp/motion/SubsenseMotionDetection/test/CMakeLists.txt, cpp/motion/SubsenseMotionDetection/test/test_subsense_motion_detection.cpp, cpp/motion/SubsenseMotionDetection/test/test_subsense_streaming_motion_detection.cpp
**Issues:**
- https://github.com/openmpf/openmpf/issues/1812
- https://github.com/openmpf/openmpf-projects/pull/9
- https://github.com/openmpf/openmpf-projects/pull/10 
- https://github.com/openmpf/openmpf/pull/1811
- https://github.com/openmpf/openmpf-components/pull/369
- https://github.com/openmpf/openmpf-contrib-components/pull/92
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/126
- https://github.com/openmpf/openmpf-python-component-sdk/pull/80
- https://github.com/openmpf/openmpf-java-component-sdk/pull/66
- https://github.com/openmpf/openmpf-docker/pull/216
- https://github.com/openmpf/openmpf-build-tools/pull/47
- https://github.com/openmpf/openmpf.github.io/pull/186
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Update copyright to 2024.
